global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'serverapp'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['serverapp:80']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']
  
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
